# -*- coding: utf-8 -*-
"""Learnbay-Python-Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-sILjK9o4djN71VbYOen4MQO1GK2dZC
"""

# The following code asks for user to input 4 numbers 
# in 4 different numer bases binary, octal, decimal and hexadecimal respectively) 
# and outputs a 4*4 table with conversions in all the number bases.


usr_input = {'Binary':int(input('Enter a binary number: '), base=2), 
             'Octal':int(input('Enter an octal number: '), base=8),
             'Decimal':int(input('Enter a decimal number: ')),
             'HexDec':int(input('Enter a hexadecimal number: '), base=16)
             }

print()

columns = ['Binary', 'Octal', 'Decimal', 'HexDec']

for row in range(0, 2):
  for column in range(0, 4):
    if row == 0:
     print(columns[column], end='\t\t')
    elif row != 0:
      print(bin(usr_input[columns[column]]), end='\t\t')
      print(oct(usr_input[columns[column]]), end='\t\t')
      print(int(usr_input[columns[column]]), end='\t\t')
      print(hex(usr_input[columns[column]]), end='\t\t')
      print()
  print()